<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Comm_Fault" Id="{1dc9a71f-1d9d-4004-a8e1-7e7bbec0a7cb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Comm_Fault
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>