<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Emg_Stop" Id="{6cda912b-c67a-4d63-a638-3cc993734bb7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Emg_Stop
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>