<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Jog_Joint" Id="{8f1e9f20-798c-4943-94cf-09207669ac31}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Jog_Joint
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>