<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Jog_Cartesian" Id="{2d54d00d-baff-42ca-81cb-c86a3364ebdc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Jog_Cartesian
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>