<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_Manual" Id="{47b8b6cb-7452-434b-a087-5026a0bf9b80}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Manual
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>